[package]
name = "quad-files"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-jsutils = "0.1.4"

[dev-dependencies]
egui-macroquad = "0.15.0"
macroquad = "0.4.13"
egui = "0.31.0"
